feat(edit): wisata & bus
meinhere/budal-travel pull request #44
Opened 2024-05-25 13:55 UTC by rrayhka

update wisata masih error untuk lat and long, sisanya update bisa semua

2024-05-25 14:33 UTC, meinhere commented on app/Http/Controllers/DashboardWisataController.php
> +            "titik_long" => $request->titik_long
"titik_lokasi" => $request->titik_lat . ',' . $request->titik_long,

2024-05-25 14:33 UTC, meinhere requested changes
tambahin validasi dan benarkan titik_lokasi wisata

2024-05-25 14:51 UTC, rrayhka commented on app/Http/Controllers/DashboardWisataController.php
> +            "titik_long" => $request->titik_long
cek bang

2024-05-26 05:35 UTC, meinhere approved these changes
sipp kelas bang akhyar

2024-05-26 05:36 UTC, merged